// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>

      <title>Notes Application</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <form action='/notes' method='get'>
        <div>
          <label htmlFor="email">Email</label> <br />
          <input type="text" id="email" placeholder="Email" /> <br /> <br />
          <label htmlFor="password">Password</label> <br />
          <input type="text" id="password" placeholder="Password" /> <br />
          <input type="submit" value="Submit" />
        </div>
      </form>
    </div>
  )
}
